### ISSUE TITLE
Jpeg muxed to Motion photo is bugged

### ISSUE THREAD

**Issue by IamRysing** [PetrVys/MotionPhoto2#6] opened 2024-10-22 00:22 UTC
Hi there! Thank you for creating this script. 

I have just been facing issues trying to batch Mux my photos from my iCloud to my Samsung tablet. Specifically, that the JPEG Motion photos created by this script seem to be unable to display the motion on the Samsung Gallery App and Google Photos App.

To illustrate my issue, here is the JPEG and MOV I will be trying to turn into a motion photo:
[JPEG motion photo test.zip](https://github.com/user-attachments/files/17468058/JPEG.motion.photo.test.zip)

Where after running the script within windows:
![Screenshot 2024-10-22 105008](https://github.com/user-attachments/assets/ae585035-c73e-431d-91ea-099017cef56e)

I am left with this result:
[IMG_3338 result.zip](https://github.com/user-attachments/files/17468069/IMG_3338.result.zip)

However, when I try to view this motion photo on Samsung's Gallery App, I am provided the option to "View motion photo", however the video muxed does not show up:

https://github.com/user-attachments/assets/b2bf48f5-46e6-4cf8-8724-86ad3eb4699d

As for viewing on Google photos, the option to view the motion photo is not present:

![Screenshot_20241022_104837_Photos](https://github.com/user-attachments/assets/3b98e46a-3b53-43bb-a183-a28560e39ea7)

From my use of the program, this issue does not occur for HEIF/HEIC files.

(To provide further details, I am using the latest update for both Samsung Gallery App & Google Photos app, using v1.3 of MotionPhoto2 and using exiftool-12.99_64)

**Comment by Tkd-Alex** [comment] 2024-10-22 09:56
Hello, I'm currently working on a python implementation of this software, I found the same issue with .jpg

**Comment by PetrVys** [comment] 2024-10-22 10:01
Hi,

Thanks for a very detailed report. I'll leave the issues with Samsung app to issue #5, please follow that one - I hope that once I remux the video to mp4 and copy metadata to be more android style it'll be accepted...

As far as the issues in google photos, I am also able to replicate them - but not in exactly the same way as you. Once the file is uploaded to cloud, it is detected as motion photo... But the playback fails. I'll try to tweak things and hopefully fix it - it seems that there is some issue with parsing of XMP metadata.

In any case, as a hint (that will not work for this particular case, though): If GPhoto fails to show a picture as a live photo, try to upload it to cloud, delete local copy and download it back. The local playback sometimes works and sometimes does not and is dictated by the particular phone's libraries (it may as well only work for motion photos taken by that particular phone model). But once in cloud, GPhotos tries to parse many possible motion photo formats (of which this script creates one) and when downloaded back to the phone/tablet, it converts it to be compatible with that model.

**Comment by PetrVys** [comment] 2024-10-22 10:09
> Hello, I'm currently working on a python implementation of this software, I found the same issue with .jpg

Strange thing is, I have a lot of old motion photos in JPG format, but from iPhones incapable of heic (OG iP SE mostly), and these jpegs do work for me...

Anyway, if small fixes fail to work, muxing jpegs using the MotionPhoto v1 format like in https://github.com/mihir-io/MotionPhotoMuxer is the way to go (we just need to fix the footer to be compatible with Samsung app, as it is currently cutting off few necessary bytes from the footer)

**Comment by PetrVys** [comment] 2024-10-22 10:21
> Hello, I'm currently working on a python implementation of this software, I found the same issue with .jpg

Also, do ping me here once you have something at least partially usable... I started this to teach myself PowerShell, thinking that at least it'll not require any runtime to run on Windows... But honestly, powershell is quite horrible and slow for bit-banging individual bytes to files... I wouldn't mind switching to python for this myself :-)

**Comment by Tkd-Alex** [comment] 2024-10-22 10:49
> > Hello, I'm currently working on a python implementation of this software, I found the same issue with .jpg
> 
> Strange thing is, I have a lot of old motion photos in JPG format, but from iPhones incapable of heic (OG iP SE mostly), and these jpegs do work for me...
> 
> Anyway, if small fixes fail to work, muxing jpegs using the MotionPhoto v1 format like in https://github.com/mihir-io/MotionPhotoMuxer is the way to go (we just need to fix the footer to be compatible with Samsung app, as that implementation is currently cutting off few necessary bytes from the footer)

Edit: I've done another test muxing .jpg works only with vertical image (taken with front-camera), photo with rear-camera in landscape mode cause a playback issue on gphoto

**Comment by PetrVys** [comment] 2024-10-22 11:27
> [IMG_1497.zip](https://github.com/user-attachments/files/17474926/IMG_1497.zip)
> 
> This archive contains a .HEIC file and .MP4. Both files where takeout from Google Photo, in the past the images was uploaded with "compress method", so the .HEIC file as the signature of .JPG file, my python script automatically change the ext if detect this issue.

Interestingly, google does convert the apple gainmap format to adobe one and not to google one.

In what direction are you changing the extension? By now it is a HDR JPG file, not heic - do not mux it as heic, otherwise mpvd top level box is added and the resulting motion photo is broken.

**Comment by Tkd-Alex** [comment] 2024-10-22 11:31
I've tried a bunch of 200 pictures, the only issue is with the one taken with the iPhone 14 pro max, the ones with the iPhone 11 are motioned without any issue :)

**Comment by Tkd-Alex** [comment] 2024-10-22 11:37
> > [IMG_1497.zip](https://github.com/user-attachments/files/17474926/IMG_1497.zip)
> > This archive contains a .HEIC file and .MP4. Both files where takeout from Google Photo, in the past the images was uploaded with "compress method", so the .HEIC file as the signature of .JPG file, my python script automatically change the ext if detect this issue.
> 
> Interestingly, google does convert the apple gainmap format to adobe one and not to google one.
> 
> In what direction are you changing the extension? By now it is a HDR JPG file, not heic - do not mux it as heic, otherwise mpvd top level box is added and the resulting motion photo is broken.

I've just rename the file .HEIC with .JPG extension (the same can be achieved with `exiftool '-FileName<%f.$FileType' -ext HEIC .`) - Could you please try mi archive with your powershell script?

As I already said the files .HEIC and .MP4 are originally takeout from Google Photos. Taken and uploaded with "compress mode" with an iPhone 14 Pro Max.

**Comment by PetrVys** [comment] 2024-10-22 11:54
![IMG_1497mp](https://github.com/user-attachments/assets/6fedc0b6-a4ed-44ad-971a-65af9fee63f4)
It fails in the same way - motion is detected, but not played back

**Comment by PetrVys** [comment] 2024-10-22 12:11
> I've just rename the file .HEIC with .JPG extension (the same can be achieved with `exiftool '-FileName<%f.$FileType' -ext HEIC .`) - Could you please try mi archive with your powershell script?

It's probably easier to detect this by the header of the file - if first 4 bytes of the file are 0xFFD8FFE0 it is JPG, if bytes 5-8 are "ftyp" it is some derivative of MP4, i.e. heic. You can avoid one exiftool call :-)

**Comment by Tkd-Alex** [comment] 2024-10-22 18:20
I don't understand why with https://github.com/doodspav/motionphoto the mp4 is played on gphotos and not with our implementation - same files 😕

**Comment by PetrVys** [comment] 2024-10-22 18:42
That's because all other implementations actually implement [the Google standard](https://developer.android.com/media/platform/motion-photo-format), e.g. MotionPhoto ver 1, whereas this one implements the weird Samsung standard "mpv2". You can see that in ver1, the video is actually part of the footer (e.g. you have some magic bytes, then "MotionPhoto_Data", then video and then again magic bytes; and the values in XMP are filled with correct numbers. Whereas in ver2, you have photo + 8-byte separator + video + full trailer at the end. The important pointers are only in the trailer, the values in google XMP header are filled with nonsense.

I'll try to find some time to add the code to mux ver1 this week for JPGs, as it is clearly more compatible...

**Comment by Tkd-Alex** [comment] 2024-10-22 19:16
> That's because all other implementations actually implement [the Google standard](https://developer.android.com/media/platform/motion-photo-format), e.g. MotionPhoto ver 1, whereas this one implements the weird Samsung standard "mpv2". You can see that in ver1, the video is actually part of the footer (e.g. you have some magic bytes, then "MotionPhoto_Data", then video and then again magic bytes; and the values in XMP are filled with correct numbers. Whereas in ver2, you have photo + 8-byte separator + video + full trailer at the end. The important pointers are only in the trailer, the values in google XMP header are filled with nonsense.
> 
> I'll try to find some time to add the code to mux ver1 this week for JPGs, as it is clearly more compatible...

Ok but the issue is not about the jpeg, because I've tried other jpeg for example the one taken with iPhone 11 works flawless - only the one with iPhone 14 pro max (attached) doesn't work - we should be able to find the issue and make Live also this picture with the latest motion protocol

**Comment by PetrVys** [comment] 2024-10-22 19:21
The issue is, I do not have any actual MP files in mpv2 format that are JPGs. Yes, they seem to - mostly - work, but all the MP JPGs I could find so far were of the vanilla Google variety. Which is probably good, since it is published Google "standard", whereas my code is reverse engineered by looking at pictures from Samsung phones in binary viewer :-).

I'll first try to update the code to create the pictures more like Galaxy S23, it seems that one is much closer to the vanilla Google implementation (but still does work for HEICs). Hopefully that'll work for JPGs as well :-)

**Comment by IamRysing** [comment] 2024-10-22 22:55
> The issue is, I do not have any actual MP files created by camera in mpv2 format that are JPGs. I just extrapolated the HEIF format and it - mostly - worked. But all the MP JPGs I could find so far were of the vanilla Google variety. Which is probably good, since it is published Google "standard", whereas my code is reverse engineered by looking at pictures from Samsung phones in binary viewer :-).
> 
> I'll first try to update the code to create the pictures more like Galaxy S23, it seems that one is much closer to the vanilla Google implementation (but still does work for HEICs). Hopefully that'll work for JPGs as well :-)

I actually own a Samsung S20 FE (Non 5G Model) and am willing to go out and take a JPEG Motion photo for you. Additionally it seems like my Samsung Tab S9 has support for Motion Photos 3?

https://www.sammyfans.com/2024/02/24/one-ui-6-1s-improved-motion-photo-feature-coming-for-these-older-samsung-devices/

So I should be able to provide a Jpeg and Heif Motion Photo (V3)

Please let me know if you need me to provide them 😃

**Comment by PetrVys** [comment] 2024-10-23 04:31
Definitely, please :-)
You can push it to my other repository or just upload it here.
In the meantime, I’ve implemented the S23 ver3 format into python code… but it does not help with the iphone 14/15jpgs… The difference was effectively only correct google header and version signature…

**Comment by IamRysing** [comment] 2024-10-23 06:22
> Definitely, please :-) You can push it to my other repository or just upload it here. In the meantime, I’ve implemented the S23 ver3 format into python code… but it does not help with the iphone 14/15jpgs… The difference was effectively only correct google header and version signature…

Phew! That took a bit, since I'm very brand new to Github, 

But I sent a pull request over https://github.com/PetrVys/MotionPhotoSamples/pulls :)

**Comment by PetrVys** [comment] 2024-10-23 06:49
Thanks, accepted.

Git is very powerful, but a bit intimidating for new users, indeed. Hope you'll find some use for your new superpower :-)

**Comment by PetrVys** [comment] 2024-10-23 07:20
Ok, so the JPG muxing is different from HEIC muxing for the trailer. I'll look into it today...

**Comment by Tkd-Alex** [comment] 2024-10-23 08:16
samsung Galaxy A34 5G, .jpg motion

![IMG_20241023_091216_154](https://github.com/user-attachments/assets/44370d94-6fca-48a1-b965-a2e42b709405)

**Comment by PetrVys** [comment] 2024-10-23 14:14
Thanks, added to the list.

@IamRysing : Can you try the attachment? Hopefully it works like this
[IMG_3338.LIVE.ZIP](https://github.com/user-attachments/files/17493047/IMG_3338.LIVE.ZIP)

**Comment by IamRysing** [comment] 2024-10-23 14:51
> Thanks, added to the list.
> 
> @IamRysing : Can you try the attachment? Hopefully it works like this [IMG_3338.LIVE.ZIP](https://github.com/user-attachments/files/17493047/IMG_3338.LIVE.ZIP)

Amazing! It worked on both the Samsung Gallery App and the Google Photos App:

https://github.com/user-attachments/assets/5b4401d9-6e66-4fc0-bb50-8ea4cf69fe0a


https://github.com/user-attachments/assets/6a54a7df-17e3-4dc0-88be-127c5f7e4c5b


I guess all that's left for me is to learn to use the python implementation if you are still intending to abandon the .cmd script 😅 

Thank you for the swift fix!

May I ask if this was using MPv2 or MPv3?

**Comment by PetrVys** [comment] 2024-10-24 10:33
closing issue, it seems the new code creates valid JPG motionphotos.

**Closed by PetrVys** 2024-10-24 10:33 UTC
